-- NudgeOn policy/resource database
-- Public resource data is readable by everyone. All writes happen through the server.
-- Personal profile, saved resources, and notifications require Supabase Auth.

CREATE TYPE public.resource_kind AS ENUM ('policy', 'institution', 'program', 'seminar', 'housing_notice');
CREATE TYPE public.resource_status AS ENUM ('draft', 'review', 'published', 'archived');
CREATE TYPE public.application_status AS ENUM ('unknown', 'upcoming', 'open', 'always', 'closed');
CREATE TYPE public.eligibility_result AS ENUM ('likely', 'needs_review', 'unlikely', 'missing_information');
CREATE TYPE public.saved_resource_stage AS ENUM ('interested', 'checking_eligibility', 'preparing_documents', 'applied', 'completed', 'dismissed');
CREATE TYPE public.notification_channel AS ENUM ('email', 'push', 'sms');

CREATE TABLE public.resource_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  sort_order int NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.resource_categories (slug, name, description, sort_order) VALUES
  ('counseling', '상담·마음건강', '청년미래센터, 대학상담센터, 마음건강 지원', 10),
  ('welfare', '생활·복지', '생활비, 청년수당, 긴급복지, 문화지원', 20),
  ('career', '일자리·커리어', '취업지원, 일경험, 채용, 멘토링', 30),
  ('housing', '주거', 'LH·SH, 청년주택, 월세·전세 지원', 40),
  ('education', '교육·역량', '세미나, 무료 강의, 직업훈련, 자격증', 50),
  ('community', '관계·활동', '청년센터 소모임, 커뮤니티, 문화·체육', 60),
  ('finance-legal', '금융·법률', '채무, 금융교육, 노동·주거 법률상담', 70)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order;

CREATE TABLE public.resources (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  external_id text,
  source_key text NOT NULL,
  kind public.resource_kind NOT NULL DEFAULT 'policy',
  status public.resource_status NOT NULL DEFAULT 'review',
  title text NOT NULL,
  summary text,
  details text,
  support_details text,
  organization_name text,
  application_url text,
  reference_url text,
  contact text,
  application_method text,
  required_documents text,
  application_status public.application_status NOT NULL DEFAULT 'unknown',
  application_starts_at timestamptz,
  application_ends_at timestamptz,
  always_open boolean NOT NULL DEFAULT false,
  online_available boolean,
  cost_free boolean,
  region_codes text[] NOT NULL DEFAULT '{}',
  keywords text[] NOT NULL DEFAULT '{}',
  raw_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_updated_at timestamptz,
  verified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_key, external_id)
);

CREATE INDEX resources_status_category_idx ON public.resources (status, application_status);
CREATE INDEX resources_application_ends_idx ON public.resources (application_ends_at);
CREATE INDEX resources_region_codes_gin ON public.resources USING gin (region_codes);
CREATE INDEX resources_keywords_gin ON public.resources USING gin (keywords);
CREATE INDEX resources_search_idx ON public.resources USING gin (
  to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(summary, '') || ' ' || coalesce(details, ''))
);

CREATE TABLE public.resource_category_links (
  resource_id uuid NOT NULL REFERENCES public.resources(id) ON DELETE CASCADE,
  category_id bigint NOT NULL REFERENCES public.resource_categories(id) ON DELETE RESTRICT,
  is_primary boolean NOT NULL DEFAULT false,
  confidence numeric(4,3),
  PRIMARY KEY (resource_id, category_id)
);

CREATE TABLE public.eligibility_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id uuid NOT NULL REFERENCES public.resources(id) ON DELETE CASCADE,
  rule_type text NOT NULL CHECK (rule_type IN (
    'age', 'region', 'income_median_percent', 'income_other', 'employment',
    'education', 'housing', 'marital_status', 'special', 'exclusion'
  )),
  operator text NOT NULL DEFAULT 'manual_review' CHECK (operator IN (
    'between', 'in', 'not_in', 'lte', 'gte', 'equals', 'contains', 'manual_review'
  )),
  value jsonb NOT NULL,
  explanation text,
  source_text text,
  required boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX eligibility_rules_resource_idx ON public.eligibility_rules (resource_id, rule_type);

CREATE TABLE public.application_steps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id uuid NOT NULL REFERENCES public.resources(id) ON DELETE CASCADE,
  step_order int NOT NULL,
  title text NOT NULL,
  description text,
  link_url text,
  document_name text,
  UNIQUE (resource_id, step_order)
);

CREATE TABLE public.resource_sources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id uuid REFERENCES public.resources(id) ON DELETE CASCADE,
  source_type text NOT NULL CHECK (source_type IN ('api', 'official_site', 'partner', 'instagram_submission', 'manual')),
  source_name text NOT NULL,
  source_url text NOT NULL,
  canonical boolean NOT NULL DEFAULT false,
  fetched_at timestamptz,
  content_hash text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.user_connection_profiles (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  birth_year int CHECK (birth_year BETWEEN 1900 AND 2100),
  region_codes text[] NOT NULL DEFAULT '{}',
  education_status text,
  employment_status text,
  housing_status text,
  household_size int CHECK (household_size > 0),
  income_median_band text CHECK (income_median_band IN ('under_60', 'under_100', 'under_150', 'over_150', 'unknown')),
  needs text[] NOT NULL DEFAULT '{}',
  available_contact_methods text[] NOT NULL DEFAULT '{}',
  consented_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.user_saved_resources (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  resource_id uuid NOT NULL REFERENCES public.resources(id) ON DELETE CASCADE,
  stage public.saved_resource_stage NOT NULL DEFAULT 'interested',
  eligibility public.eligibility_result NOT NULL DEFAULT 'missing_information',
  eligibility_details jsonb NOT NULL DEFAULT '{}'::jsonb,
  checklist jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, resource_id)
);

CREATE TABLE public.notification_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  resource_id uuid REFERENCES public.resources(id) ON DELETE CASCADE,
  category_id bigint REFERENCES public.resource_categories(id) ON DELETE CASCADE,
  channel public.notification_channel NOT NULL,
  destination text,
  days_before int[] NOT NULL DEFAULT '{7,1}',
  notify_when_opens boolean NOT NULL DEFAULT true,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (resource_id IS NOT NULL OR category_id IS NOT NULL)
);

CREATE TABLE public.ingestion_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_key text NOT NULL,
  status text NOT NULL CHECK (status IN ('running', 'succeeded', 'failed', 'partial')),
  fetched_count int NOT NULL DEFAULT 0,
  inserted_count int NOT NULL DEFAULT 0,
  updated_count int NOT NULL DEFAULT 0,
  error_count int NOT NULL DEFAULT 0,
  error_summary text,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz
);

CREATE TABLE public.review_queue (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  resource_id uuid REFERENCES public.resources(id) ON DELETE CASCADE,
  submission_url text,
  extracted_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_by uuid REFERENCES auth.users(id),
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER resources_set_updated_at BEFORE UPDATE ON public.resources
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER connection_profiles_set_updated_at BEFORE UPDATE ON public.user_connection_profiles
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER saved_resources_set_updated_at BEFORE UPDATE ON public.user_saved_resources
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.resource_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resource_category_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eligibility_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.application_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resource_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_connection_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_saved_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingestion_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_queue ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public_read_categories" ON public.resource_categories FOR SELECT USING (active);
CREATE POLICY "public_read_published_resources" ON public.resources FOR SELECT USING (status = 'published');
CREATE POLICY "public_read_published_category_links" ON public.resource_category_links FOR SELECT
USING (EXISTS (SELECT 1 FROM public.resources r WHERE r.id = resource_id AND r.status = 'published'));
CREATE POLICY "public_read_published_rules" ON public.eligibility_rules FOR SELECT
USING (EXISTS (SELECT 1 FROM public.resources r WHERE r.id = resource_id AND r.status = 'published'));
CREATE POLICY "public_read_published_steps" ON public.application_steps FOR SELECT
USING (EXISTS (SELECT 1 FROM public.resources r WHERE r.id = resource_id AND r.status = 'published'));
CREATE POLICY "public_read_published_sources" ON public.resource_sources FOR SELECT
USING (EXISTS (SELECT 1 FROM public.resources r WHERE r.id = resource_id AND r.status = 'published'));

CREATE POLICY "users_read_own_profile" ON public.user_connection_profiles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "users_insert_own_profile" ON public.user_connection_profiles FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "users_update_own_profile" ON public.user_connection_profiles FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "users_delete_own_profile" ON public.user_connection_profiles FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "users_manage_own_saved_resources" ON public.user_saved_resources FOR ALL
USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "users_manage_own_notifications" ON public.notification_rules FOR ALL
USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

GRANT SELECT ON public.resource_categories, public.resources, public.resource_category_links,
  public.eligibility_rules, public.application_steps, public.resource_sources TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_connection_profiles,
  public.user_saved_resources, public.notification_rules TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- Tighten the earlier rehearsal prototype only when that optional table exists.
-- A fresh Supabase project may apply the policy DB before the rehearsal migration.
DO $$
BEGIN
  IF to_regclass('public.social_rehearsal_sessions') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "anon_select_rehearsals" ON public.social_rehearsal_sessions';
    EXECUTE 'DROP POLICY IF EXISTS "anon_update_rehearsals" ON public.social_rehearsal_sessions';
    EXECUTE 'DROP POLICY IF EXISTS "anon_delete_rehearsals" ON public.social_rehearsal_sessions';
    EXECUTE 'REVOKE SELECT, UPDATE, DELETE ON public.social_rehearsal_sessions FROM anon';
  END IF;
END;
$$;
